name = "ai-sandbox-prototype"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://aisandbox.1ai.my.id/api"
NEXT_PUBLIC_MSW_ENABLED = "true"
