// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/access-denied" | "/[locale]/dashboard" | "/[locale]/login" | "/[locale]/models" | "/[locale]/models/[id]" | "/[locale]/models/[id]/public" | "/[locale]/models/[id]/runs/[runId]" | "/[locale]/models/new" | "/[locale]/ranking" | "/[locale]/ranking/compare" | "/[locale]/reviews" | "/[locale]/reviews/[id]" | "/[locale]/settings"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/access-denied": { "locale": string; }
  "/[locale]/dashboard": { "locale": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/models": { "locale": string; }
  "/[locale]/models/[id]": { "locale": string; "id": string; }
  "/[locale]/models/[id]/public": { "locale": string; "id": string; }
  "/[locale]/models/[id]/runs/[runId]": { "locale": string; "id": string; "runId": string; }
  "/[locale]/models/new": { "locale": string; }
  "/[locale]/ranking": { "locale": string; }
  "/[locale]/ranking/compare": { "locale": string; }
  "/[locale]/reviews": { "locale": string; }
  "/[locale]/reviews/[id]": { "locale": string; "id": string; }
  "/[locale]/settings": { "locale": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
